steps:
  - label: "Timeout soft_fail test (default grace period)"
    command: "echo 'Sleeping for 10 minutes (will be timed out after 1)...' && sleep 600"
    timeout_in_minutes: 1
    soft_fail:
      - exit_status: 90
